name: CI/CD

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: ["codellama", "llama-2", "mistral", "mixtral", "pythia"]
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_ENVIRONMENT: ci-llm-finetuning

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal pyyaml pandas

      - name: Prep config and data for CI
        run: |
          python ci/prep_for_ci.py --config=config/${{ matrix.config }}.yml --data=data/sqlqa.jsonl
          echo `wc -l data/sqlqa.jsonl | awk '{print $1}'` lines in test data
          echo Config:
          cat config/${{ matrix.config }}.yml

      - name: Run training job on Modal
        run: |
          modal run src.train --config=config/${{ matrix.config }}.yml --data=data/sqlqa.jsonl

      - name: Check training results
        run: |
          python ci/check_loss.py

      - name: Check inference results
        run: |
          python ci/check_inference.py
